gradle.ext.refinedArchitectVersion = "0.15.3"

dependencyResolutionManagement {
    repositories {
        maven {
            url = "https://maven.pkg.github.com/refinedmods/refinedarchitect"
            credentials {
                username = "anything"
                password = "\u0067hp_oGjcDFCn8jeTzIj4Ke9pLoEVtpnZMP4VQgaX"
            }
        }
    }
    versionCatalogs {
        create("libs") {
            from("com.refinedmods.refinedarchitect:refinedarchitect-catalog:${gradle.ext.refinedArchitectVersion}")
        }
    }
}

rootProject.name = 'refinedarchitect-template'
include 'refinedarchitect-template-platform-common'
include 'refinedarchitect-template-platform-neoforge'
include 'refinedarchitect-template-platform-fabric'
