name: Publish release
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  publish-release:
    uses: refinedmods/refinedarchitect/.github/workflows/publish-release.yml@v0.11.2
    secrets: inherit
    with:
      project-name: 'Refined Architect template'
      announce: false
      mutation-testing: false
      sonarqube: false